#!/usr/bin/env python3
"""docs/plan-status.md must not claim a file is missing when it is not.

THE FILE THAT EXISTS TO PREVENT STALE CLAIMS WENT STALE. Its own opening line
is "which numbered steps of the implementation plan are actually done, as
opposed to claimed", and it carried this for several changes after it stopped
being true:

    **1.5's second acceptance is unmet.** "Every rule in the pack maps to a row
    in `docs/teardown.md`." That file does not exist.

It does exist. `scripts/teardown.py` built it, `verify.sh` gates on every FDA
rule having a row in it, and the gate was mutation-tested. The status was
written when it was true, the work landed in a later change, and nobody went
back.

WHAT THIS CATCHES, WHICH IS ONE SPECIFIC THING. A sentence naming a file in
backticks and saying, nearby, that it does not exist, when the file is on disk.
That is the shape the staleness took and it is the shape a script can judge.

WHAT IT CANNOT CATCH. A row marked "partial" that is now done, a "not started"
that is now started, a reason that has stopped being the real reason. Those
need somebody to read the file, and this check is not a substitute for that. It
is one tripwire on the failure that already happened twice: this document also
said "Phase 1 is complete" while three of SPEC.md's Phase 1 steps were unbuilt.

    python3 scripts/check-plan-status.py
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(ROOT, "docs", "plan-status.md")

# Phrases that assert a thing is absent. Matched within a window after a
# backticked path, so "docs/teardown.md ... does not exist" is caught and
# "docs/teardown.md is generated by a script that does not exist yet" three
# paragraphs later is not.
#
# "there is no" was in this list and had to come out. It matched "there is no
# paid contract" in a sentence that happened to follow a mention of
# `docs/continuity.md`, and reported a document that exists as claimed missing.
# A check that cries wolf gets muted, and a muted check is worse than an absent
# one. Every phrase below is about a FILE existing rather than about anything
# being absent in general.
ABSENT = re.compile(
    r"(does not exist|do not exist|does not yet exist|is missing|are missing"
    r"|was never written|no such file)",
    re.IGNORECASE,
)

PATHLIKE = re.compile(r"^[A-Za-z0-9_./-]+$")

# How far after a path mention an absence claim still counts as being about it.
WINDOW = 160


def looks_like_path(token):
    t = token.strip()
    if not PATHLIKE.match(t):
        return False
    return "/" in t or t.endswith((".md", ".sh", ".py", ".ts", ".tsx", ".json", ".yml"))


def main():
    if not os.path.exists(DOC):
        print("    FAILED: %s does not exist" % os.path.relpath(DOC, ROOT))
        return 1
    text = io.open(DOC, encoding="utf-8").read()

    problems = []
    checked = 0
    for m in re.finditer(r"`([^`]+)`", text):
        token = m.group(1)
        if not looks_like_path(token):
            continue
        path = os.path.join(ROOT, token)
        if not os.path.exists(path):
            continue  # the claim, whatever it is, is about a file that is absent
        checked += 1

        # Look ahead from the end of the backticked path for an absence claim.
        window = text[m.end(): m.end() + WINDOW]
        hit = ABSENT.search(window)
        if hit:
            line = text[: m.start()].count("\n") + 1
            problems.append((line, token, window[max(0, hit.start() - 30): hit.end() + 20].strip()))

    if problems:
        print("    FAILED: %d claim(s) that a file is absent, about files that exist:" % len(problems))
        for line, token, snippet in problems:
            print("        line %d: `%s` ... %s" % (line, token, snippet.replace("\n", " ")))
        print()
        print("    This document exists to say what is actually done rather than what was")
        print("    claimed. A status written when it was true and left behind when the work")
        print("    landed is the failure it was created to record.")
        return 1

    print("    %d path(s) referenced in plan-status, none of them claimed absent while present"
          % checked)
    return 0


if __name__ == "__main__":
    sys.exit(main())
