#!/usr/bin/env python3
"""Generate a bill of materials for this repository, and check it with this tool.

The dogfood. A checker whose own bill of materials has never been checked is
selling something it has not tried.

It came out of SPEC.md 2.8: writing the continuity plan meant claiming the
licence protects a customer, which meant looking at whether the licence was
declared, which it was not, in any of the twelve package.json files. That gap
is fixed and `scripts/check-own-licence.py` keeps it fixed. This goes one step
further and asks what a real generator produces from this repository, and what
this tool says about it.

BE FAIR TO THE GENERATOR. syft is a good tool and produced several files in
`fixtures/corpus`. The gaps below are mostly what a pnpm lockfile does not
carry: a lockfile records names, versions and integrity hashes for resolution,
not producers or licences. That is a fact about the ecosystem rather than a
defect in syft, and a document claiming otherwise would be the kind of unfair
teardown `docs/teardown.md` refuses to be.

WHAT THE COMPONENTS ARE. Almost all of them are DEVELOPMENT dependencies:
platform binaries for sharp, which Next.js pulls in for image handling. The
engine itself declares zero runtime dependencies and a CI step enforces that.
An SBOM of this repository is therefore mostly a picture of a build toolchain,
and saying "85 components" without saying that would overstate the surface.

    python3 scripts/self-sbom.py --generate <path-to-syft>   rebuild
    python3 scripts/self-sbom.py --check                     offline, gate
"""
import io
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SBOM = os.path.join(ROOT, "docs", "self", "stratifypro.cdx.json")
RESULT = os.path.join(ROOT, "docs", "self", "self-check.json")
DOC = os.path.join(ROOT, "docs", "self-check.md")
CLI = os.path.join(ROOT, "apps", "cli", "dist", "index.js")
PACK = "cisa-2026-v2.1"


def generate(syft):
    os.makedirs(os.path.dirname(SBOM), exist_ok=True)
    r = subprocess.run(
        [syft, "scan", "dir:.", "--output", "cyclonedx-json=" + SBOM, "--quiet"],
        cwd=ROOT, capture_output=True, text=True,
    )
    if r.returncode != 0:
        print("    FAILED: syft: %s" % (r.stderr or r.stdout)[:300])
        return 1

    # Only the serialNumber is dropped. It is a fresh random urn:uuid on every
    # run and carries no information a reader can use.
    #
    # THE TIMESTAMP IS KEPT, and the first version of this script removed it
    # for the same tidiness reason. That was not tidying: CISA-MD-006 requires
    # an SBOM timestamp, so stripping it ADDED a finding, and this page would
    # have published a failure caused by its own post-processing and attributed
    # it to the generator. 266 findings became 267.
    #
    # A document about how honest a tool is cannot manufacture the evidence.
    doc = json.load(io.open(SBOM, encoding="utf-8"))
    doc.pop("serialNumber", None)
    io.open(SBOM, "w", encoding="utf-8", newline="\n").write(
        json.dumps(doc, indent=2, sort_keys=True) + "\n"
    )

    r = subprocess.run(
        [os.environ.get("NODE", "node"), CLI, "check", SBOM, "--pack", PACK, "--format", "json"],
        cwd=ROOT, capture_output=True, text=True,
    )
    if not r.stdout.strip().startswith("{"):
        print("    FAILED: the CLI produced no JSON: %s" % (r.stderr or r.stdout)[:300])
        return 1
    result = json.loads(r.stdout)
    io.open(RESULT, "w", encoding="utf-8", newline="\n").write(
        json.dumps(result, indent=2, sort_keys=True) + "\n"
    )
    io.open(DOC, "w", encoding="utf-8", newline="\n").write(render(doc, result))
    print("    wrote %s, %s and %s"
          % (os.path.relpath(SBOM, ROOT), os.path.relpath(RESULT, ROOT), os.path.relpath(DOC, ROOT)))
    return 0


def summarise(doc, result):
    components = doc.get("components") or []
    by_rule = {}
    for f in result.get("findings", []):
        e = by_rule.setdefault(f["ruleId"], {"n": 0, "title": f["title"], "severity": f["severity"]})
        e["n"] += 1
    return components, by_rule


def render(doc, result):
    components, by_rule = summarise(doc, result)
    n = len(components)
    counts = result.get("counts", {})
    L = []
    L.append("# What this tool says about its own bill of materials")
    L.append("")
    L.append(
        "A checker whose own bill of materials has never been checked is selling "
        "something it has not tried. This is that, generated by command and "
        "regenerated by `verify.sh` on every build."
    )
    L.append("")
    L.append("## The document")
    L.append("")
    L.append("| | |")
    L.append("|---|---|")
    L.append("| Generated by | `%s` |" % (doc.get("metadata", {}).get("tools", {}) and "syft" or "syft"))
    L.append("| Format | CycloneDX %s |" % doc.get("specVersion", "?"))
    L.append("| Components | %d |" % n)
    L.append("| Checked against | `%s` |" % PACK)
    L.append("| Findings | **%d** |" % len(result.get("findings", [])))
    L.append("")
    L.append(
        "**Almost every component is a development dependency**, mostly platform "
        "binaries that Next.js pulls in for image handling. The engine declares "
        "zero runtime dependencies and a CI step enforces it. Quoting the "
        "component count without saying that would overstate the surface."
    )
    L.append("")

    L.append("## What it found")
    L.append("")
    L.append("| Rule | Severity | Components | What it asks for |")
    L.append("|---|---|---|---|")
    for rule_id, e in sorted(by_rule.items(), key=lambda kv: (-kv[1]["n"], kv[0])):
        L.append("| `%s` | %s | %d | %s |" % (rule_id, e["severity"], e["n"], e["title"]))
    L.append("")
    universal = sorted(r for r, e in by_rule.items() if e["n"] == n and n > 0)
    if universal:
        L.append(
            "**%d rule%s fail%s on every single component**: %s."
            % (len(universal), "" if len(universal) == 1 else "s",
               "s" if len(universal) == 1 else "",
               ", ".join("`%s`" % r for r in universal))
        )
        L.append("")

    L.append("## Whose fault this is, stated fairly")
    L.append("")
    L.append(
        "Not the generator's. syft is a good tool and produced several of the files "
        "in `fixtures/corpus`. A pnpm lockfile records names, versions and integrity "
        "hashes so that installs resolve; it does not record a producer or a licence "
        "for each package. A generator reading a lockfile cannot emit what the "
        "lockfile does not contain."
    )
    L.append("")
    L.append(
        "That is the finding, and it is about the ecosystem rather than about one "
        "tool. The default output of a standard generator, run the standard way on "
        "a real project, does not meet the CISA minimum elements. The corpus says "
        "the same thing across 21 files from other projects; this says it about us."
    )
    L.append("")

    L.append("## The number that is not zero, and the one that is")
    L.append("")
    L.append(
        "There are **%d findings** and **%d at severity error**. Those are "
        "consistent: `%s` contains no rule at severity error, because the CISA "
        "minimum elements document is not a regulation and no rule citing it "
        "should read as a filing blocker. `--fail-on error` would exit 0 on this "
        "document, which is correct and is exactly the kind of thing a reader "
        "should be told rather than left to discover."
        % (len(result.get("findings", [])), counts.get("error", 0), PACK)
    )
    L.append("")
    L.append("## Reproducing this")
    L.append("")
    L.append("```")
    L.append("python3 scripts/self-sbom.py --generate /path/to/syft")
    L.append("```")
    L.append("")
    L.append(
        "The document is committed at `docs/self/stratifypro.cdx.json` and the "
        "result at `docs/self/self-check.json`. `verify.sh` re-runs the engine over "
        "the committed document and fails if the result has moved, so this page "
        "cannot drift from what the tool actually says."
    )
    L.append("")
    return "\n".join(L) + "\n"


def check():
    """Offline. Re-run the engine over the committed SBOM and compare."""
    for p in (SBOM, RESULT, DOC):
        if not os.path.exists(p):
            print("    FAILED: %s missing; run --generate" % os.path.relpath(p, ROOT))
            return 1
    if not os.path.exists(CLI):
        print("    SKIPPED: the CLI is not built")
        return 0

    r = subprocess.run(
        [os.environ.get("NODE", "node"), CLI, "check", SBOM, "--pack", PACK, "--format", "json"],
        cwd=ROOT, capture_output=True, text=True,
    )
    if not r.stdout.strip().startswith("{"):
        print("    FAILED: the CLI produced no JSON")
        return 1
    fresh = json.loads(r.stdout)
    stored = json.load(io.open(RESULT, encoding="utf-8"))

    if fresh.get("findings") != stored.get("findings"):
        print("    FAILED: the engine no longer produces the stored result for our own SBOM.")
        print("            fresh: %d findings, stored: %d"
              % (len(fresh.get("findings", [])), len(stored.get("findings", []))))
        print("            Run: python3 scripts/self-sbom.py --generate <syft>")
        return 1

    doc = json.load(io.open(SBOM, encoding="utf-8"))
    if io.open(DOC, encoding="utf-8").read() != render(doc, stored):
        print("    FAILED: docs/self-check.md no longer matches the stored result")
        return 1

    print("    %d components, %d findings, and the published page is the engine's own output"
          % (len(doc.get("components") or []), len(stored.get("findings", []))))
    return 0


if __name__ == "__main__":
    if "--generate" in sys.argv:
        i = sys.argv.index("--generate")
        syft = sys.argv[i + 1] if len(sys.argv) > i + 1 else "syft"
        sys.exit(generate(syft))
    sys.exit(check())
